In [ ]:
import numpy as np

In [27]:
vecteur = np.array([1, 2, 3])
print(vecteur)
print("Nb dim : ", vecteur.ndim)
print("Shape  : ", vecteur.shape)
print()

# Vecteur colonne
# n lignes, 1 colonne
vecteur_colonne = vecteur.reshape(-1, 1)
print(vecteur_colonne)
print("Nb dim : ", vecteur_colonne.ndim)
print("Shape  : ", vecteur_colonne.shape)
print()

# Vecteur ligne
# 1 ligne, n colonnes
vecteur_ligne = vecteur.reshape(1, -1)
print(vecteur_ligne)
print("Nb dim : ", vecteur_ligne.ndim)
print("Shape  : ", vecteur_ligne.shape)
print()

# Matrice A 3x3
A = np.array([
  [2, 0, 1], 
  [1, 3, 0], 
  [0, 1, 2]
])
print(A)
print("Nb dim : ", A.ndim)
print("Shape  : ", A.shape)
print()

# row major => 
B = np.array([
  [2, 0], 
  [1, 3], 
  [0, 1]
])
print(B)
print("Nb dim : ", B.ndim)
print("Shape  : ", B.shape)
print()



[1 2 3]
Nb dim :  1
Shape  :  (3,)

[[1]
 [2]
 [3]]
Nb dim :  2
Shape  :  (3, 1)

[[1 2 3]]
Nb dim :  2
Shape  :  (1, 3)

[[2 0 1]
 [1 3 0]
 [0 1 2]]
Nb dim :  2
Shape  :  (3, 3)

[[2 0]
 [1 3]
 [0 1]]
Nb dim :  2
Shape  :  (3, 2)



In [32]:
# A * V
# A = 3 li et 3 col
# V = 3 li et 1 col
# On a autant de colonnes dans operand 1 que de lignes dans operand 2 => ca passe
# x x x     a
# x x x  *  b 
# x x x     c
# r est vect colonnes à 3 composantes
r = np.dot(A, vecteur_colonne)
print("A x v_colonne")
print(r)
print("Nb dim : ", r.ndim)
print("Shape  : ", r.shape)
print()

r = np.dot(B.T, vecteur_colonne)
print("Transpose(B) x v")
print(r)
print("Nb dim : ", r.ndim)
print("Shape  : ", r.shape)
print()


# passe pas
# on a 1 colonne dans op 1 mais 3 lignes dans op 2
# r = np.dot(vecteur_colonne, A)


# A * V
# vecteur est 
r = np.dot(A, vecteur)
print("A x vecteur")
print(r)
print("Nb dim : ", r.ndim)
print("Shape  : ", r.shape)
print()

# V * B
# r est un vecteur ligne avec autant composantes que le nb de colonnes de la matrice
# r est vect ligne à 2 composantes
r = np.dot(vecteur_ligne, B)
print("vecteur_ligne x B")
print(r)
print("Nb dim : ", r.ndim)
print("Shape  : ", r.shape)
print()

# V * A
# r est vect ligne à 3 composantes
r = np.dot(vecteur_ligne, A)
print("vecteur_ligne x A")
print(r)
print("Nb dim : ", r.ndim)
print("Shape  : ", r.shape)
print()

r = np.dot(vecteur, A)
print("vecteur x A")
print(r)
print("Nb dim : ", r.ndim)
print("Shape  : ", r.shape)
print()





A x v_colonne
[[5]
 [7]
 [8]]
Nb dim :  2
Shape  :  (3, 1)

Transpose(B) x v
[[4]
 [9]]
Nb dim :  2
Shape  :  (2, 1)

A x vecteur
[5 7 8]
Nb dim :  1
Shape  :  (3,)

vecteur_ligne x B
[[4 9]]
Nb dim :  2
Shape  :  (1, 2)

vecteur_ligne x A
[[4 9 7]]
Nb dim :  2
Shape  :  (1, 3)

vecteur x A
[4 9 7]
Nb dim :  1
Shape  :  (3,)

